year = int(input("Enter the year: "))
genre = input("Enter the genre: ")
album = input("Enter the album: ")
title = input("Enter the title: ")
artist = input("Enter the artist: ")

print("-----------------------")
print("SONG DETAILS")
print("-----------------------")
print("Year Released:",year)
print("Genre:", genre)
print("Album:", album)
print("Title:", f'"{title}"')
print("Artist", artist)
